#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

./scripts/build-chart

mkdir -p bin
GO_BUILD_FLAGS="-gcflags=all=-trimpath=${GOPATH} -asmflags all=-trimpath=${GOPATH}"
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s -w"
fi
LINKFLAGS="-X github.com/rancher/helm-project-operator/pkg/version.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/helm-project-operator/pkg/version.GitCommit=$COMMIT $LINKFLAGS"
CGO_ENABLED=0 go build $GO_BUILD_FLAGS -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/helm-project-operator
if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
    GOOS=darwin go build -ldflags "$LINKFLAGS" -o bin/helm-project-operator-darwin
    GOOS=windows go build -ldflags "$LINKFLAGS" -o bin/helm-project-operator-windows
fi
