#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

CHART=${CHART:-"project-operator-example"}
VERSION=0.0.0

helm package charts/${CHART} --destination bin/${CHART}
base64 -i bin/${CHART}/${CHART}-${VERSION}.tgz > bin/${CHART}/${CHART}.tgz.base64
rm bin/${CHART}/${CHART}-${VERSION}.tgz