#!/bin/bash
set -e

BUILD_TARGET=${BUILD_TARGET:-"helm-project-operator"}

# We don't do this for helm-locker
if [[ "${BUILD_TARGET}" != "helm-project-operator" ]]; then
  exit
fi

source $(dirname $0)/version

cd $(dirname $0)/..

CHART=${CHART:-"project-operator-example"}
VERSION=0.0.0

helm package charts/${CHART} --destination bin/${CHART}
base64 -i bin/${CHART}/${CHART}-${VERSION}.tgz > cmd/${BUILD_TARGET}/fs/${CHART}.tgz.base64
rm bin/${CHART}/${CHART}-${VERSION}.tgz