#!/bin/bash
set -e
set -x
source $(dirname $0)/version

K3S_VERSION="v1.23.17-k3s1"

CLUSTER_NAME="e2e-hpo-test-$K3S_VERSION"

CLUSTER_NAME=$CLUSTER_NAME K3S_VERSION=$K3S_VERSION ./scripts/setup-cluster
BASEDIR="/tmp/e2e-hpo-test/$CLUSTER_NAME"
mkdir -p $BASEDIR

k3d kubeconfig get $CLUSTER_NAME > $BASEDIR/kubeconfig.yaml

cd tests/e2e && IMAGE=$IMAGE KUBECONFIG=$BASEDIR/kubeconfig.yaml go test -v -count=1 ./... -timeout 30m