#!/bin/bash
set -e

source $(dirname $0)/version
DOCKER_TARGET=${DOCKER_TARGET:-"-${BUILD_TARGET}"}

cd $(dirname $0)/..
echo Building ${IMAGE} ...
DOCKERFILE=package/Dockerfile${DOCKER_TARGET}
docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
