#!/bin/bash

BUILD_TARGET=${BUILD_TARGET:-"helm-project-operator"}

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${COMMIT}${DIRTY}"
fi

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

HELM_IMAGE_TAG=${HELM_IMAGE_TAG:-${TAG}}
if [ "$TAG" == "$COMMIT" ]; then
  HELM_CHART_VERSION="0.0.0-dev.${COMMIT}"
else
  HELM_CHART_VERSION=${HELM_IMAGE_TAG/v/}
fi

if echo $TAG | grep -q dirty; then
    TAG="v0.0.0-dev.1"
    HELM_IMAGE_TAG=$TAG
    HELM_CHART_VERSION=${HELM_CHART_VERSION_DEV:-${HELM_IMAGE_TAG/v/}}
fi
IMAGE=${IMAGE:-${REPO}/${BUILD_TARGET}:${TAG}}